### ISSUE TITLE
Why don't you just use `npm` to do this?

### ISSUE THREAD

**Issue by StoneCypher** [TomPrograms/super-updater#1]
The relevant command is `npm --depth 9999 update`

**Comment by TomPrograms** [comment]
The standard NPM update command doesn’t update dev dependencies. Also, when using the NPM update command sometime I have experience a lag time between the package release and the update working though NPM update, which is an issue not present here.

**Comment by mumairofficial** [comment]
If you're on yarn, simply execute this:

```
yarn upgrade-interactive --latest
```

and see magic!

**Comment by TomPrograms** [comment]
I don’t personally use yarn which is partly why I built this tool.

**Comment by StoneCypher** [comment]
[If you want it to handle dev deps](https://docs.npmjs.com/cli-commands/update.html), you also throw the `--dev` flag

```shell
npm update --dev --depth 9999
```

**Comment by StoneCypher** [comment]
it's worth noting that this updates in a different order than shrinkwrap

this means that updates from third party services like prbear and snyk will essentially always require a rebase, and could plausibly fault build orders (the stuff yarn was invented over, which is rare but does happen and is nearly impossible to fix, esp around `node-gyp`)
